linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 150

linters:
  disable-all: true
  enable:
    # Essential linters only
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Standard Go analyzer
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Find unused code
    - typecheck     # Type checking

issues:
  exclude-rules:
    # Exclude linting issues in test files
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosimple
        - gocyclo
    # Exclude issues in helper files
    - path: datastructure_helper/
      linters:
        - errcheck

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - .git

