linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell
    - goconst
    - dupl
    - gocyclo
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - gocyclo

run:
  timeout: 5m
  tests: true

